[build]
  publish = "_build/html/"
  command = "make netlify"
  environment = { BASE_URL = "https://esphome.io/", DOXYGEN = "../doxybin/doxygen" }

[context.beta]
  environment = { BASE_URL = "https://beta.esphome.io/", DOXYGEN = "../doxybin/doxygen" }

# A basic redirect rule
[[redirects]]
  from = "/esphomeyaml/*"
  to = "/:splat"
